name: Lingo.dev i18n

on:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write

jobs:
  i18n-web:
    name: Run i18n for web (UI strings)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: lingodotdev/lingo.dev@main
        env:
          GH_TOKEN: ${{ github.token }}
        with:
          api-key: ${{ secrets.LINGODOTDEV_API_KEY }}
          pull-request: true
          pull-request-title: "i18n: Lingo (web)"
          commit-message: "i18n: Lingo Translation Update (web)"
          working-directory: "apps/web"
          parallel: true

  i18n-docs:
    name: Run i18n for docs (content)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: lingodotdev/lingo.dev@main
        env:
          GH_TOKEN: ${{ github.token }}
        with:
          api-key: ${{ secrets.LINGODOTDEV_API_KEY }}
          pull-request: true
          pull-request-title: "i18n: Lingo (docs)"
          commit-message: "i18n: Lingo Translation Update (docs)"
          working-directory: "apps/docs"
          parallel: true

  i18n-accelerate:
    name: Run i18n for accelerate (UI strings)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: lingodotdev/lingo.dev@main
        env:
          GH_TOKEN: ${{ github.token }}
        with:
          api-key: ${{ secrets.LINGODOTDEV_API_KEY }}
          pull-request: true
          pull-request-title: "i18n: Lingo (accelerate)"
          commit-message: "i18n: Lingo Translation Update (accelerate)"
          working-directory: "apps/accelerate"
          parallel: true
